---
- name: Debian - install runit
  apt:
    name=runit
    state=present
    update_cache=yes
    cache_valid_time=3600

- name: Ubuntu - start and enable runit service
  service:
    name=runsvdir
    enabled=yes
    state=started
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != "xenial"

- name: Ubuntu - start and enable runit service on systemd
  sytemd:
    name=runit
    enabled=yes
    state=started
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial"

- name: Debian - start and enable runit service
  service:
    name=runit-start
    enabled=yes
    state=started
  when: ansible_distribution|lower == "debian"

